# Numpy array

## Array

* La estructura central de NumPy.
* Representa datos de una manera estructurada.
* Indexado.
* Acceso a uno o muchos elementos.

In [1]:
import numpy as np # asi se importa numpy

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

**Aqui convertimos una simple lista a un array que puede utilizar numpy**

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr) # para ver si se convitio a un tipo de dato array

numpy.ndarray

In [6]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # la matriz debe contener la misma cantidad de datos por cada columna
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[0] # los arrays empiezan desde cero

1

In [9]:
arr[0] + arr[5]

7

In [11]:
matriz[0] # nos data la columna completa

array([1, 2, 3])

In [12]:
matriz[0,2]

3

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[1:6] # con un start y end

array([2, 3, 4, 5, 6])

In [17]:
arr[2:] # solo con el start pero sin el end

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[::3]

array([1, 4, 7])

In [19]:
arr[-1] # muestra el ultimo dato

9

In [20]:
arr[-3]

7

In [21]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
matriz[1: ,0: 2]

array([[4, 5],
       [7, 8]])