# Crearcion de arrays

In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
sin_saltos = np.arange(0,20)
con_saltos = np.arange(0,20, 2)
print(sin_saltos,con_saltos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [ 0  2  4  6  8 10 12 14 16 18]


In [4]:
np.zeros((10, 5)) # el 10 son las columnas y el 5 son filas y zeros nos genera una matriz de zeos

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.linspace(0, 10, 100) # x es donde quiero que inicie, y hasta donde quiero que llegue, cuantos datos quiero

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand() # para valores random

0.9586039457013409

In [15]:
np.random.rand(4) # me genera un vector

array([0.14977091, 0.36548662, 0.98122178, 0.82105204])

In [17]:
np.random.rand(4,4) # genera una matriz

array([[0.99027516, 0.58230302, 0.06749942, 0.14938643],
       [0.43129445, 0.83283408, 0.65786305, 0.22636374],
       [0.43361108, 0.26741165, 0.33808029, 0.60558162],
       [0.38270564, 0.89039238, 0.18485526, 0.8153719 ]])

In [18]:
np.random.randint(1, 15) # aqui defino el rango en el cual se puede lanzar un numero aleatorio

10

In [19]:
np.random.randint(1, 100, (10,10)) # genera una matriz con numeros aleatorios

array([[74, 22, 64, 41, 73, 68, 27, 84,  1, 46],
       [68, 46, 59, 53,  4, 55,  5, 65, 70, 95],
       [42, 96, 58, 12, 47, 91, 16, 94, 46, 24],
       [84, 19, 62, 59, 42, 37, 69,  4, 46, 37],
       [37, 93, 71, 27, 42, 67, 82, 12, 97, 50],
       [ 6, 78, 76, 15, 14,  3, 89, 94, 42, 51],
       [83, 37, 42, 54, 17, 67, 97, 96, 19, 83],
       [99, 57, 49, 65, 24, 90, 20, 84, 50, 77],
       [ 9, 83, 90, 47, 33, 83, 41, 69, 68, 14],
       [20,  6, 53, 83, 74,  1, 20, 45, 76, 86]])