In [1]:
import numpy as np

In [7]:
scalar = np.array(42) # es aquel arreglo que tiene un solo valor
print(scalar)
scalar.ndim

42


0

In [6]:
vector = np. array([1,2,3]) # es aquella arreglo que tiene mas de un valor
print(vector)
vector.ndim # para saber el numero de dimensiones en nuestro scalar

[1 2 3]


1

In [10]:
matriz = np. array([[1,2,3], [4, 5, 5]]) # es aquella que puede tener varios arreglos dentro de un arreglo
print(matriz)
matriz.ndim 

[[1 2 3]
 [4 5 5]]


2

In [11]:
tensor = np.array([[[1,2,3], [4,5,6], [7, 8, 9]],[[0,1,2],[0,3,4],[12,34,4]],[[22,4,5],[1,23,2],[4,56,33]]]) # el tensor es el que tiene matrices dentro de una matriz
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 0  1  2]
  [ 0  3  4]
  [12 34  4]]

 [[22  4  5]
  [ 1 23  2]
  [ 4 56 33]]]


3

## Agregar o eliminar dimensiones

In [12]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [14]:
expand = np.expand_dims(np.array([1,2,3]), axis=0) #axis=0 son filas y el axis=1 son columnas
print(expand)
expand.ndim

[[1 2 3]]


2

In [16]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) # eliminar o controlar las dimensiones que no se esten usando
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Ejercicio de la clase:
Definir un tensor con 5 dimensiones e intentar sumar una dimension en cualquiera de sus ejes y eliminar dimensiones basura


In [36]:
# agregar dimesion
tensor = np.array([[[[[1, 2,3], [4, 5,6], [1,2,7]]]]])
print(tensor, tensor.ndim)
tensor_6 = np.array(tensor, ndmin = 6)
print(tensor_6, tensor_6.ndim)


[[[[[1 2 3]
    [4 5 6]
    [1 2 7]]]]] 5
[[[[[[1 2 3]
     [4 5 6]
     [1 2 7]]]]]] 6


In [38]:
# eliminar  dimesion basura
reducir = np.squeeze(tensor_6)
print(reducir, reducir.ndim)

[[1 2 3]
 [4 5 6]
 [1 2 7]] 2
